<?php

/*
    Activity statistics functions
    
    Supported statistics:
    - Activity "like" statistics data
    - Activity "participent" statistics data
    - Activity "viewed" statistics data
    - Activity "Not like" statistics data
    - The rate of like/viewed
    - The rate of "not like"/like
    - The rate of participent/viewed
    - The rate of participent/like
*/

function activity_statistics_like($aid){
	
}

function activity_statistics_notLike($aid){
	
}

function activity_statistics_rate_NotLike_like($aid){
    
}

function activity_statistics_participent($aid){
	
}

function activity_statistics_viewed($aid){
	
}

function activity_statistics_rate_like_viewed($aid){
	
}

function activity_statistics_rate_participent_viewed($aid){
	
}

function activity_statistics_rate_participent_like($aid){
	
}

