<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/7
 * Time: 15:51
 */

namespace service\survey\models;

use \service\base\db\SimpleAR;

class LimeSurveyAnswers extends SimpleAR
{

    public static $survey_id;

    public static function getDb()
    {
        return \Yii::$app->db_survey; // TODO: Change the autogenerated stub
    }

    public static function getSurveyId($survey_id = 0)
    {
        self::$survey_id = $survey_id;
    }

    public static function tableName()
    {
        return 'lime_survey_' . self::$survey_id;
    }

}