<?php
namespace service\survey\models;

class LimeSurveyLanguageSetting extends ARecord
{

    public static function primaryKey()
    {
        return ['surveyls_survey_id'];
    }

    public static function ma()
    {

    }

    public static function tableName()
    {
        return 'lime_surveys_languagesettings'; // TODO: Change the autogenerated stub
    }

    public static function getSurveyDetail($id,$unique_code)
    {
        if(empty($id)) return [];
        $sql = '';
        foreach ($id as $value){
            $sql .= ' SELECT l.*,t.* FROM '.static::tableName().' l LEFT JOIN lime_tokens_'.$value.' t ON 1=1 WHERE t.lastname="'.$unique_code.'" AND l.surveyls_survey_id = '.$value.' UNION';
        }
        $sql = substr($sql,0,-5);
//        return $sql;

//        $sql = '
//        SELECT l.*,t.* FROM '.static::tableName().' l LEFT JOIN lime_tokens_481314 t ON 1=1 WHERE t.firstname="朱振法" AND l.surveyls_survey_id = 481314
//        UNION
//        SELECT l.*,t.* FROM '.static::tableName().' l LEFT JOIN lime_tokens_618972 t ON 1=1 WHERE t.firstname="朱振法" AND l.surveyls_survey_id = 618972
//        ';
        $survey = \Yii::$app->db_survey->createCommand($sql)->queryAll();

        return $survey;
    }
}