<?php
namespace service\survey\models;


class LimeSurvey extends ARecord
{

    public static function tableName()
    {
        return 'lime_surveys'; // TODO: Change the autogenerated stub
    }

    public static function getSurveys(array $map = [], $offset = 0, $limit = 6)
    {
        $where[] = 'AND';
        $where[] = ['active' => 'Y'];
        $query = static::find()->from(['l' => static::tableName()])
            ->select(['l.sid', 's.surveyls_survey_id', 's.surveyls_title'])
            ->where($where)
            ->andWhere($map)
            ->join('LEFT JOIN ', LimeSurveyLanguageSetting::tableName() . ' AS s', 'l.sid = s.surveyls_survey_id');
        $list = $query->orderBy('datecreated desc')->offset($offset)->limit($limit)->asArray()->all();
        $count = $query->count();
        return [$list, $count];
    }
}