<?php
namespace service\exam\models;

class LimeToken extends ARecord
{

    public static $survey_id;

    public static function getDb()
    {
        return \Yii::$app->db_survey; // TODO: Change the autogenerated stub
    }

    public static function getSurveyId($survey_id = 0)
    {
        self::$survey_id = $survey_id;
    }

    public static function tableName()
    {
        return 'lime_tokens_' . self::$survey_id;
    }



    public static function createTable($survey_id = 666666)
    {

        $con = \Yii::$app->db_survey;
        $tableName = 'lime_tokens_' . $survey_id;
        $key = 'idx_token_token_' . $survey_id . '_' . rand(10000, 99999);
        $sql = "
        
        DROP TABLE IF EXISTS `$tableName`;
        CREATE TABLE `$tableName` (
          `tid` int(11) NOT NULL AUTO_INCREMENT,
          `participant_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `firstname` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `lastname` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `email` text COLLATE utf8mb4_unicode_ci,
          `emailstatus` text COLLATE utf8mb4_unicode_ci,
          `token` varchar(35) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
          `language` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `blacklisted` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
          `sent` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
          `remindersent` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
          `remindercount` int(11) DEFAULT '0',
          `completed` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
          `usesleft` int(11) DEFAULT '1',
          `validfrom` datetime DEFAULT NULL,
          `validuntil` datetime DEFAULT NULL,
          `mpid` int(11) DEFAULT NULL,
          PRIMARY KEY (`tid`),
          KEY `$key` (`token`)
        ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
        
        ";
        $con->createCommand($sql)->execute();
    }



    

}