<?php
namespace service\exam\models;

class PlanExams extends \service\base\db\SimpleAR
{
    public static function tableName()
    {
        return 'plan_exams'; // TODO: Change the autogenerated stub
    }
}