 {
    "button":[
        {	
          "type":"view",
          "name":"首页",
          "key":"WX_MENU_HOME",
          "url": "<?=$this->buildUrl('https://dev.lasooo.me');?>"
        },
        {	
          "type":"view",
          "name":"订单",
          "key":"WX_MENU_ORDER",
          "url": "<?=$this->buildUrl('https://dev.lasooo.me/order');?>"
        },
        {	
          "type":"view",
          "name":"我",
          "key":"WX_MENU_PROFILE",
          "url": "<?=$this->buildUrl('https://dev.lasooo.me/home');?>"
        }
    ]
 }

